[project]
name = "llm-speed-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "markdown2>=2.5.3",
    "markdown>=3.7",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "openai>=1.61.0",
    "pandas>=2.2.3",
]
